### ISSUE TITLE
Consider removing prefix section in `write_output_prepare.R`

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/nanostring#104] opened 2024-11-21 14:23 UTC
This section of the code:
https://github.com/nf-core/nanostring/blob/e765843c16d2bfe90c72e31a7a3719466d1bdfb0/bin/write_out_prepared_gex.R#L59-L62

Causes that sometimes the prefix is appended to the output file name. It does not behave consistently.

**Comment by alanmmobbs93** [comment] 2024-11-21 19:30
@nschcolnicov I worked a little bit on this because it was affecting the nf-test I was developing for the module. The inconsistency was caused by the order in which the module is executed. As we know, sometimes one input file is processed first (with "No_HK" prefix, for example) and in other occasions this file is processed later or last. So, this changes de output names "randomly", and the test sometimes are successful and sometimes not.

The problem was fixed with a sort() approach, making sure that the files are always processed in the same order [PR #103](https://github.com/nf-core/nanostring/pull/103)

**Closed** 2024-11-22 15:25 UTC
